--- 
title : Best Hospitals Switzerland
date : '2021-03-18'
servicename : newsweek
categories :
  - Post
tags :
  - R
  - HTML
  - hospital
  - ranking
description : Newsweek shows the third year the World's Best Hospitals.
draft: false

dateformat : '%Y-%m-%dT%H:%M:%S'
outputpath : public
mainfile : main.Rmd
tmpdir : publictmp
countries : c('Austria','Switzerland','Canada','France','Germany','USA')

# Build data
build:
 path : build
 swissdata : nw_hospitals_swiss.csv

restapi:
 path : rest
 restfile : api.json

# Static data
static:
 path : static
 countryfile : nw_countries.csv
 hospitalfile : nw_hospitals.csv

# Content
content:
 path : content

# Public
public:
 path : public
 
# Eventlog
events:
 path : static
 staticlog : eventlog.csv
 entries:
 - source : newsweek data 2019
   resource : newsweek
 - source : newsweek data 2020
   resource : newsweek
 - source : newsweek data 2021
   resource : newsweek

